apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-microservice-deployment
    labels:
        app: my-deploy-microservice
        version: v1
        tier: backend
        environment: learning
spec:
    template:
        metadata:
            labels:
                app: ms-1-deployment
                version: v1
                tier: backend
                environment: learning
        spec:
            containers:
                -   name: my-microservice-container-c001
                    imagePullPolicy: IfNotPresent
                    image: ubuntu:latest
                    command:
                        - /bin/bash
                        - -c
                        - |
                            echo "Hello, this is my microservice running in a Kubernetes cluster!"
                            sleep infinity
    replicas: 3
    selector:
        matchExpressions:
            -   key: app
                operator: In
                values:
                    - ms-1-deployment