apiVersion: v1
kind: ReplicationController
metadata:
    name: my-app-rc
    labels:
        app: my-app-rc #label for the replication controller instance
spec:
    template:
        metadata:
            labels:
                app: my-linux-app-rc #label for the pod
                tier: backend
        spec:
            containers:
            - name: my-linux-app
              image: ubuntu
              command: ["bash", "-c", "while [ true ]; do echo Hello, Kubernetes!; sleep 5 ; done"]
    replicas: 3
    selector:
        app: my-linux-app-rc